--- 
clone: 
  depth: 1
kind: pipeline
name : Nexus Alioth
version: alioth
steps:
 - name: Nexus Alioth
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh null alioth null

--- 
clone: 
  depth: 1
kind: pipeline
name : Nexus Lmi
version: lmi
steps:
 - name: Nexus Lmi
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh null lmi null

--- 
clone: 
  depth: 1
kind: pipeline
name : Nexus Apollo
version: apollo
steps:
 - name: Nexus Apollo
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh null apollo null

--- 
clone: 
  depth: 1
kind: pipeline
name : Nexus Munch
version: munch
steps:
 - name: Nexus Munch
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh null munch null
